//CommonJS, every file is module (by default)
//Modules - Encapsulated Code (only share minimum)

const names = require("./4_names")
const sayHi = require("./5_utils")
const data = require("./6_alternative")
require('./7_mind_grenade')
sayHi('susan')
sayHi(names.anita)
sayHi(names.angel)
